### ISSUE TITLE
[MS-3] - USER STORY: Tool update & delete

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#11]
As the **creator of a tool entry**, I can **update or delete the entry** so that **so the tool can be permanently be updated or deleted if needed**

## Acceptance Criteria

- Information of selected tool should be fetched by ID and fill in the form

- The tool should be updated easily by owner

- The tool can be deleted by owner

- Second confirmation for deleting tool

- Redirect to tool or home page

## Tasks

- [x] (BE) Delete & put view in backend

- [x] (FE) Update implementation with redirect

- [x] (FE) Implement message for tool update

- [x] (FE) Delete implementation with second confirmation and redirect

- [x] (FE) Implement message for tool deletion
