### ISSUE TITLE
[MS-3] - BE - TASK: Tools app setup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#12]
Setup of the tools app in Django

## Task Criteria

- [x] Initialize app by using startapp

- [x] Create model for tools

- [x] Add tools app to settings, urls, views
