### ISSUE TITLE
[MS-3] - FE - TASK: Create form to add tool entries

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#13]
Create a form to a new tool entry as a user

## Task Criteria

- [x] User needs account to create entry

- [x] Categories can be selected as emoji

- [x] Validation of all fields

- [x] Slug for url is creared automatically (BE)

- [x] Add redirect to tool page

- [x] Add confirmation message
