### ISSUE TITLE
[MS-3] - FE - TASK: Create tool details page

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#15]
Page with a detail view for the tool and functionality to upvote and comment.

## Task Criteria

- [x] A page with all information of the tool: Title, descriptions, categories, author, category

- [x] Author details showing

- [x] Upvote feature

- [x] [Comment feature](https://github.com/DennisSchenkel/sessionminds-frontend/issues/28)
