### ISSUE TITLE
[MS-3] - USER STORY: Tools creation

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#16]
As a **user**, I can **create a new tool entry** so that **the tool is visible in the list of tools and on its detail page**

## Acceptance Criteria

- A new tool entry can be created

- A tool has title, short description, long description, category, image, steps

- A tool entry is linked to a user who created it

## Tasks

- [x] [(BE) Tools app setup](https://github.com/DennisSchenkel/sessionminds-frontend/issues/12)

- [x] [(FE) Create form to add tool entries](https://github.com/DennisSchenkel/sessionminds-frontend/issues/13)

- [x] [(FE) Create tools list](https://github.com/DennisSchenkel/sessionminds-frontend/issues/14)

- [x] [(FE) Create tool details page](https://github.com/DennisSchenkel/sessionminds-frontend/issues/15)
