### ISSUE TITLE
DRAFT: [MS-3] - BE - TASK: Add multiple images to tool entry

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#17]
After creating a tool, the author can add or remove multiple images to the tool.

## Task Criteria

- [ ] Images can be linked to a specific tool

- [ ] Only the author can add images

- [ ] Use a separate DB table with all images in it and one related tool for each image
