### ISSUE TITLE
DRAFT: [MS-3] - USER STORY: Add images to tool

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#18]
As an **author of a tool**, I can **add multiple images to it** so that **users can better understand the instructions**

## Acceptance Criteria

- Acceptance criteria 1

- Acceptance criteria 2

- Acceptance criteria 3

## Tasks

- [ ] [(BE) Add multiple images to tool](https://github.com/DennisSchenkel/sessionminds-frontend/issues/17)

- [ ] (BE/FE) Task 2

- [ ] (BE/FE) Task 3
