### ISSUE TITLE
[MS-0] - FE - TASK: Setup React app

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#19]
Initial setup of the React application

## Task Criteria

- [x] Local setup of React app

- [x] Fix all dependencies and version issues

- [x] Establish connection to API

- [x] Establish API authentication

- [x] Add Bootstrap 

- [x] Deploy to heroku
