### ISSUE TITLE
[MS-1] - USER STORY: User profiles

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#2]
As a **user**, I can **create a user profile** so that **I can log in and use the app according to my permissions**

## Acceptance Criteria

- Profile app and according module has to be added to Django

- Profile can be created, seen, updated and deleted.

- Users can only update/delete their own profile

## Tasks

- [x] [(BE) Profile app setup](https://github.com/DennisSchenkel/sessionminds-frontend/issues/3)

- [x] [(FE) Profile information page](https://github.com/DennisSchenkel/sessionminds-frontend/issues/4)

- [x] [(FE) Create/Update profile form](https://github.com/DennisSchenkel/sessionminds-frontend/issues/5)
