### ISSUE TITLE
[MS-0] - FE - TASK: Create Header

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#21]
Create the header area with logo, navigation, search and authentication feature.

## Task Criteria

- [x] Create and implement logo

- [x] Implement Main Navigation

- [x] Implement Search

- [x] Add Login/Register/Logout Buttons
