### ISSUE TITLE
[MS-4] - USER STORY: Votes setup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#22]
As a **user**, I can **vote for a tool** so that **the tool get a better scoring**.
As a **user**, I can **see the amount of votes of each tool** so that **I have an indication of the tools quality**.

## Acceptance Criteria

- For each tool, every user has the chance to vote one time.

- Each tool shows the amount of votes it received.

- A user can undo the vote.

- Tools can be sorted by amounts of votes.

## Tasks

- [x] [(BE) Votes app setup](https://github.com/users/DennisSchenkel/projects/3/views/1?pane=issue&itemId=78271851)

- [x] [(FE) Show votes for each tool](https://github.com/users/DennisSchenkel/projects/3/views/1?pane=issue&itemId=78328579)

- [x] [(FE) Implement voting functionality](https://github.com/users/DennisSchenkel/projects/3/views/1?pane=issue&itemId=78329001)

- [x] (FE) Sort tools by amount of votes
