### ISSUE TITLE
[MS-4] - BE - TASK: Votes app setup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#23]
Create the vote app in the backend for API use

## Task Criteria

- [x] Create app within Django

- [x] Implement functionality for users voting

- [x] Create sortable list
