### ISSUE TITLE
[MS-4] - FE - TASK: Implement voting functionality

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#25]
Implement the functionality for users to vote for tools

## Task Criteria

- [x] User can click on button to vote

- [x] Users can undo voting by clicking a button a second time

- [x] Implementation in List

- [x] Implementation in tool details view
