### ISSUE TITLE
[MS-D] - BE - TASK: Automated testing

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#26]
Testing for all profile access

## Task Criteria

- [x] Test of Profile App

- [x] Test of Tools App

- [x] Test of Topics App

- [x] Test of Votes App

- [x] Test of Comments App

- [x] Test for profile creation

- [x] Test for profile update/delete

- [x] Test for login

- [x] Test for logout

- [x] Test for correct access token behavior

- [x] Test for correct refresh token behavior
