### ISSUE TITLE
[MS-3] - BE - TASK: Automated testing for tools

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#27]
Testing for tool CRUD

## Task Criteria

- [x] Create tool test

- [x] Read tool test

- [x] Update tool test

- [x] Delete tool test
