### ISSUE TITLE
[MS-5] - BE - TASK: Setup comments app

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#29]
The comments functionality needs the setup of the comments app in django

## Task Criteria

- [x] Create comments model

- [x] Create serializer

- [x] Create POST view

- [x] Create DELETE view
