### ISSUE TITLE
[MS-1] - BE - TASK: Profile app setup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#3]
Set up the profile app in Django

## Task Criteria

- [x] Initialize app by using startapp

- [x] Add profile app to settings, urls ...

- [x] Create model for profile
