### ISSUE TITLE
[MS-5] - FE - TASK: Implement comments on tool page

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#30]
Implement comments functionality to the tool page for every user that is registered and has first and last name in the profile.

## Task Criteria

- [x] Check if profile has first and last name

- [x] User can create comment

- [x] User can delete own comments
