### ISSUE TITLE
[MS-0] - FE - TASK: Mobile friendly design

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#31]
The app should be usable on mobile as well as desktop devices.

## Task Criteria

- [x] Sidebar disappearing on mobile view

- [x] Menu smaller on mobile

- [x] Hiding unneeded parts like icons on very small screens
