### ISSUE TITLE
[MS-6] - USER STORY: Search feature

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#33]
As a **user**, I can **use a search feature** so that **I can find the tool I am looking for**

## Acceptance Criteria

- The user can find and use the search field

- When doing a search, the results are shown in a list

## Tasks

- [x] [(BE) Create search feature in backend](https://github.com/DennisSchenkel/sessionminds-frontend/issues/34)

- [x] [(FE) Create page for search results](https://github.com/DennisSchenkel/sessionminds-frontend/issues/35)

- [x] [(FE) Implement search feature](https://github.com/DennisSchenkel/sessionminds-frontend/issues/36)
