### ISSUE TITLE
[MS-1] - BE - TASK: Profile API

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#6]
Make profiles API usable to get information for all and individual profiles 

## Task Criteria

- [x] Install DjangoRestFramework

- [x] Create views to view single profiles and list of all profiles

- [x] Create view to update profile

- [x] Create view to delete profile

- [x] Add authentication & permissions
