### ISSUE TITLE
[MS-2] - USER STORY: Topics setup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#7]
Part 1: As a **user**, I can **filter tools by categories** so that **I only find tools, related to selected categories**.
Part 2: As a **user**, I can **create a tool and allocate it to a category** so that **the tool will be found when filtering for this category**.

## Acceptance Criteria

- A list of categories can be created and edited in the admin panel

- Categories have titles, icons, short descriptions and slugs

- Categories are sorted alphabetically

- Bonus: Admin (only) can create & delete categories in user frontend

## Tasks

- [x] [(BE) Categories app setup](https://github.com/DennisSchenkel/sessionminds-frontend/issues/8)

- [x] [(FE) Create categories list page](https://github.com/DennisSchenkel/sessionminds-frontend/issues/9)

- [x] [(FE) Create category page with slug](https://github.com/DennisSchenkel/sessionminds-frontend/issues/10)
