### ISSUE TITLE
[MS-2] - BE - TASK: Topics app setup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#8]
Set up the categories app in Django

## Task Criteria

- [x]  Initialize app by using startapp

- [x] Add topics app to settings, urls ...

- [x] Create views for topics

- [x] Create model for topics
