### ISSUE TITLE
[MS-2] - FE - TASK: Categories list page

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/sessionminds-frontend#9]
Create a page with all categories listed

## Task Criteria

- [x] All categories are shown

- [x] Categories are listed alphabetically

- [x] Categories show amount of related tools
